enqueue:
    sqs:
        transport:
            dsn: 'sqs:?region=%env(resolve:AWS_REGION)%&endpoint=%env(resolve:AWS_SQS_ENDPOINT)%&key=%env(resolve:AWS_KEY)%&secret=%env(resolve:AWS_SECRET)%'

        client: ~
