framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }
        transports:
            async: enqueue://sqs?receiveTimeout=1000&queue[name]=%env(resolve:IMPORTER_SQS_QUEUE)%&topic[name]=%env(resolve:IMPORTER_SQS_QUEUE)%

        routing:
            'App\Message\ImportMessage': async
