framework:
    messenger:
        transports:
            async:
                dsn: enqueue://sqs?receiveTimeout=6000&queue[name]=%env(resolve:IMPORTER_SQS_QUEUE)%&topic[name]=%env(resolve:IMPORTER_SQS_QUEUE)%
                retry_strategy:
                    max_retries: 0

        routing:
            'App\Message\ImportMessage': async
