<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSKAOx95\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSKAOx95/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSKAOx95.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSKAOx95\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSKAOx95\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SKAOx95',
    'container.build_id' => '8a501bac',
    'container.build_time' => 1560787205,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSKAOx95');
