<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Command\AwsInitCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/src/Command/AwsInitCommand.php';

$this->privates['App\\Command\\AwsInitCommand'] = $instance = new \App\Command\AwsInitCommand(($this->privates['Aws\\S3\\S3Client'] ?? $this->load('getS3ClientService.php')), 'dev');

$instance->setName('app:aws-init');

return $instance;
