<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.messenger.handler_descriptor.jzO5rOv' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
include_once $this->targetDirs[3].'/src/Handler/ImportHandler.php';
include_once $this->targetDirs[3].'/src/Service/ClientProvider.php';
include_once $this->targetDirs[3].'/src/Service/ParserProvider.php';

return $this->privates['.messenger.handler_descriptor.jzO5rOv'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\Handler\ImportHandler(new \App\Service\ClientProvider(), new \App\Service\ParserProvider(), ($this->privates['Aws\\S3\\S3Client'] ?? $this->load('getS3ClientService.php')), $this->getEnv('resolve:TOUR_STORAGE_S3_BUCKET'), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService())), []);
