<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Command\AwsInitCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/src/Command/AwsInitCommand.php';
include_once $this->targetDirs[3].'/vendor/aws/aws-sdk-php/src/AwsClientInterface.php';
include_once $this->targetDirs[3].'/vendor/aws/aws-sdk-php/src/AwsClientTrait.php';
include_once $this->targetDirs[3].'/vendor/aws/aws-sdk-php/src/AwsClient.php';
include_once $this->targetDirs[3].'/vendor/aws/aws-sdk-php/src/Sqs/SqsClient.php';

$this->privates['App\\Command\\AwsInitCommand'] = $instance = new \App\Command\AwsInitCommand(($this->privates['Aws\\S3\\S3Client'] ?? $this->load('getS3ClientService.php')), new \Aws\Sqs\SqsClient(['endpoint' => $this->getEnv('resolve:AWS_SQS_ENDPOINT'), 'version' => 'latest', 'region' => $this->getEnv('resolve:AWS_REGION'), 'credentials' => ['key' => $this->getEnv('resolve:AWS_KEY'), 'secret' => $this->getEnv('resolve:AWS_SECRET')]]), 'dev');

$instance->setName('app:aws-init');

return $instance;
