<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Command\ImportCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/src/Command/ImportCommand.php';

$this->privates['App\\Command\\ImportCommand'] = $instance = new \App\Command\ImportCommand(($this->services['message_bus'] ?? $this->load('getMessageBusService.php')));

$instance->setName('app:import-tours');

return $instance;
